set(_CATKIN_CURRENT_PACKAGE "follow_bot")
set(follow_bot_VERSION "0.0.0")
set(follow_bot_MAINTAINER "malcolm <malcolm@todo.todo>")
set(follow_bot_PACKAGE_FORMAT "2")
set(follow_bot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(follow_bot_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(follow_bot_BUILDTOOL_DEPENDS "catkin")
set(follow_bot_BUILDTOOL_EXPORT_DEPENDS )
set(follow_bot_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(follow_bot_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(follow_bot_TEST_DEPENDS )
set(follow_bot_DOC_DEPENDS )
set(follow_bot_DEPRECATED "")