rosparam set /slam_gmapping/delta 0.005
rosparam set /slam_gmapping/lstep 0.4
rosparam set /slam_gmapping/astep 0.4
rosparam set /slam_gmapping/iterations 20
rosparam set /slam_gmapping/lskip 10
rosparam set /slam_gmapping/minimumScore 100
rosparam set /slam_gmapping/particles 400
rosparam set /slam_gmapping/linearUpdate 0.2
rosparam set /slam_gmapping/angularUpdate 0.2
rosparam set /slam_gmapping/xmax 5
rosparam set /slam_gmapping/xmin -5
rosparam set /slam_gmapping/ymax 5
rosparam set /slam_gmapping/ymin -5
rosparam set /slam_gmapping/map_update_interval 1
rosparam set /slam_gmapping/maxUrange 10
rosparam set /slam_gmapping/lsigma 0.025
rosparam set /slam_gmapping/sigma 0.025
