rosparam set /slam_gmapping/delta 0.04
rosparam set /slam_gmapping/lstep 0.02
rosparam set /slam_gmapping/astep 0.02
rosparam set /slam_gmapping/lskip 10
rosparam set /slam_gmapping/particles 50
rosparam set /slam_gmapping/angularUpdate 0.1
rosparam set /slam_gmapping/linearUpdate 0.1
rosparam set /slam_gmapping/xmax 100
rosparam set /slam_gmapping/xmin -100
rosparam set /slam_gmapping/ymax 100
rosparam set /slam_gmapping/ymin -100
